export const theme = {
  fonts: {
    regular: 'Nunito_400Regular',
    medium: 'Nunito_500Medium',
    semibold: 'Nunito_600SemiBold',
    bold: 'Nunito_700Bold',
    extraBold: 'Nunito_800ExtraBold',
    black: 'Nunito_900Black',
    handwritten: 'Caveat_600SemiBold',
    handwrittenBold: 'Caveat_700Bold',
  },
  colors: {
    background: '#FFFDF8',
    surface: '#FFF8F0',
    surfaceSoft: '#F8F1E8',
    line: '#E8DED2',
    text: '#181717',
    textMuted: '#8C8680',
    purple: '#8B6FEF',
    purpleSoft: '#C9B7FF',
    pink: '#FFD0DD',
    yellow: '#FFE88C',
    green: '#80D889',
    black: '#111113',
    danger: '#E45555',
  },
  radius: {
    sm: 10,
    md: 16,
    lg: 24,
    pill: 999,
  },
  shadow: {
    soft: {
      shadowColor: '#7D695C',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.12,
      shadowRadius: 24,
      elevation: 6,
    },
    sticker: {
      shadowColor: '#7D695C',
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.14,
      shadowRadius: 12,
      elevation: 4,
    },
  },
} as const;
